apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jobportal-postgres
  namespace: jobportal-dev
spec:
  serviceName: jobportal-postgres-svc

  replicas: 1
  selector:
    matchLabels:
      app: jobportal-postgres
  template:
    metadata:
      labels:
        app: jobportal-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres

        envFrom:
            - configMapRef:
                name: jobportal-postgres-config
            - secretRef:
                name: jobportal-postgres-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
