apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobportal-postgres-pvc
  namespace: jobportal-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi