name: backend test pipeline

on:
    push: 
        branches: 
            - main


jobs:
    backend-test:
        runs-on: ubuntu-latest

        steps:
            - name: download the code
              uses: actions/checkout@v4

            - name: set up python
              uses: actions/setup-node@v5
              with:
                python-version: '3.11'


            - name: install and test code
              run: |
                pip install -r requirement.txt
                flake8 .
                pytest